# -*- coding: utf-8 -*-
"""Project.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DY7qMCQSwYlxhvVZlKrT3uGqBohEoWgS

# STEP 1: Import Libraries
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report
from sklearn.ensemble import RandomForestClassifier

# Load dataset
df = pd.read_excel("/content/Customer-Churn.xlsx")

df.head()

"""# STEP 2: Clean the Data"""

df.columns = df.columns.str.strip()
df.columns = df.columns.str.replace(" ", "", regex=False)
df.columns = df.columns.str.replace("\t", "", regex=False)

if "customerID" in df.columns:
    df = df.drop("customerID", axis=1)

df.columns

"""# STEP 3: Convert Categorical Columns to Numbers"""

le = LabelEncoder()

for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = le.fit_transform(df[col])

"""# STEP 4: Split Data into Training and Testing"""

X = df.drop("Churn", axis=1)
y = df["Churn"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""# STEP 5: Train Machine Learning Model"""

model = RandomForestClassifier()
model.fit(X_train, y_train)

"""# STEP 6: Predict & Check Accuracy"""

pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))
print("\nClassification Report:\n", classification_report(y_test, pred))

"""# STEP 7: Feature Import"""

importances = model.feature_importances_
feature_names = X.columns

feat_imp = pd.DataFrame({"Feature": feature_names, "Importance": importances})
feat_imp = feat_imp.sort_values(by="Importance", ascending=False)

feat_imp

"""# Step:8 Graph"""

plt.figure(figsize=(10,6))
sns.barplot(data=feat_imp, x="Importance", y="Feature")
plt.title("Which Features Matter for Customer Churn")
plt.show()